# Generated by Django 4.2 on 2024-12-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketballPlayers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="имя",
                    ),
                ),
                ("age", models.PositiveIntegerField(verbose_name="возраст")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "career",
                    models.BooleanField(
                        default=True,
                        help_text="продолжает карьеру",
                        null=True,
                        verbose_name="карьера",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="дата изменения"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        default=None,
                        help_text="Выберите команду",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_member",
                        related_query_name="member",
                        to="team.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "питательное вещество",
                "verbose_name_plural": "питательные вещества",
                "ordering": ("-created",),
            },
        ),
    ]
